<a href="https://colab.research.google.com/github/shaswath-29/EDA_LABORATORY_ASSIGNMENT/blob/Exp5_04.08.2026/DetectingOutliers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
df = pd.read_csv('/fraudTest.csv')

In [5]:
df.head(10)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0
5,5,2020-06-21 12:15:37,30407675418785,fraud_Daugherty LLC,kids_pets,19.55,Danielle,Evans,F,76752 David Lodge Apt. 064,...,42.1939,-76.7361,520,Psychotherapist,1991-10-13,798db04aaceb4febd084f1a7c404da93,1371816937,41.747157,-77.584197,0
6,6,2020-06-21 12:15:44,213180742685905,fraud_Romaguera Ltd,health_fitness,133.93,Kayla,Sutton,F,010 Weaver Land,...,40.5070,-123.9743,1139,"Therapist, occupational",1951-01-15,17003d7ce534440eadb10c4750e020e5,1371816944,41.499458,-124.888729,0
7,7,2020-06-21 12:15:50,3589289942931264,fraud_Reichel LLC,personal_care,10.37,Paula,Estrada,F,350 Stacy Glens,...,43.7557,-97.5936,343,"Development worker, international aid",1972-03-05,8be473af4f05fc6146ea55ace73e7ca2,1371816950,44.495498,-97.728453,0
8,8,2020-06-21 12:16:10,3596357274378601,"fraud_Goyette, Howell and Collier",shopping_pos,4.37,David,Everett,M,4138 David Fall,...,41.0001,-78.2357,3688,Advice worker,1973-05-27,71a1da150d1ce510193d7622e08e784e,1371816970,41.546067,-78.120238,0
9,9,2020-06-21 12:16:11,3546897637165774,fraud_Kilback Group,food_dining,66.54,Kayla,Obrien,F,7921 Robert Port Suite 343,...,31.6591,-96.8094,263,Barrister,1956-05-30,a7915132c7c4240996ba03a47f81e3bd,1371816971,31.782919,-96.366185,0

In [6]:

df['TotalPrice'] = df['amt']
df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,TotalPrice
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0,2.86
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0,29.84
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0,41.28
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0,60.05
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0,3.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,555714,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,...,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0,43.77
555715,555715,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,...,-95.4401,28739,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0,111.84
555716,555716,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,...,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0,86.88
555717,555717,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,...,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0,7.99
555718,555718,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,...,-97.4798,116001,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0,38.13

In [7]:
import numpy as np
TotalTransaction = df["TotalPrice"]
TotalTransaction[np.abs(TotalTransaction) > 30.0]

2          41.28
3          60.05
6         133.93
9          66.54
11         42.40
           ...
555709     46.71
555714     43.77
555715    111.84
555716     86.88
555718     38.13
Name: TotalPrice, Length: 339976, dtype: float64

In [8]:
df[np.abs(TotalTransaction) > 674.1112]

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,TotalPrice
167,167,2020-06-21 13:08:46,6011109736646996,fraud_Schumm PLC,shopping_net,1199.45,Rebecca,Erickson,F,594 Berry Lights Apt. 392,...,-77.8670,186140,English as a second language teacher,1983-02-08,249ecb7b44d6d42a8eb155833fe23c53,1371820126,34.622777,-77.827863,0,1199.45
428,428,2020-06-21 14:38:09,38530489946071,fraud_Metz-Boehm,shopping_pos,1881.53,Laura,Johns,F,95835 Garcia Rue,...,-81.9916,530,Animal technologist,1989-05-14,4c4841f79d838ed6fe2c9a0f23bfbc50,1371825489,34.709044,-82.585103,0,1881.53
720,720,2020-06-21 16:18:24,343472729187663,"fraud_Little, Gutmann and Lynch",shopping_net,705.59,Gloria,Wallace,F,234 Bridges Wells Apt. 389,...,-71.2551,1368,"Optician, dispensing",1971-08-05,695c74c63765b5b49f8cd03a0f71969f,1371831504,43.652736,-70.480378,0,705.59
728,728,2020-06-21 16:22:15,3518234918950662,"fraud_Gottlieb, Considine and Schultz",shopping_net,724.14,Barbara,Lowe,F,67210 Lori Creek,...,-96.6184,46563,Systems developer,1970-09-11,e1d1723770f702944afd2ec020fd9df0,1371831735,34.496590,-96.913335,0,724.14
951,951,2020-06-21 17:40:54,4292743669224718067,"fraud_Haley, Jewess and Bechtelar",shopping_pos,3204.98,Michael,Williams,M,35822 Clayton Street Apt. 679,...,-76.4954,5927,Art therapist,1973-06-09,cdb7839b9b57c1bd8f856c3166b0e9db,1371836454,37.480372,-77.349580,0,3204.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554553,554553,2020-12-31 17:17:41,3582754887089201,fraud_Thiel Ltd,travel,1362.77,Terrance,Mckinney,M,42965 Christopher Fords Suite 659,...,-93.6743,1383,Magazine features editor,1966-08-08,08c57e78d6fce016f73fb3450aa55850,1388510261,35.010629,-94.389187,0,1362.77
555004,555004,2020-12-31 19:43:11,4364010865167176,"fraud_Douglas, Schneider and Turner",shopping_pos,2149.66,Gary,Martinez,M,03512 Jackson Ports,...,-119.7957,276896,Immunologist,1997-03-12,418c90ecaebea2701d7fece2de5a4fed,1388518991,40.170913,-120.005205,0,2149.66
555229,555229,2020-12-31 21:08:01,36913587729122,fraud_Mayert Group,shopping_pos,1309.21,Ana,Mccormick,F,4503 Patricia Route,...,-116.4306,84106,Intelligence analyst,1971-02-11,7a848ec13987751c1b04be6006dc360f,1388524081,42.916524,-115.787654,0,1309.21
555495,555495,2020-12-31 22:36:21,630451534402,fraud_Gleason-Macejkovic,shopping_net,850.87,Rachel,Daniels,F,561 Little Plain Apt. 738,...,-86.6345,765,Immunologist,1972-06-12,ff81dabd1ed194df2fc190d5f2d28f30,1388529381,45.905236,-86.690136,0,850.87
555637,555637,2020-12-31 23:30:29,6011109736646996,fraud_Gleason-Macejkovic,shopping_net,1164.37,Rebecca,Erickson,F,594 Berry Lights Apt. 392,...,-77.8670,186140,English as a second language teacher,1983-02-08,b7f83407df7234b10f7aa2c06af06444,1388532629,34.854212,-77.711814,0,1164.37

In [10]:
df = pd.read_csv('/fraudTrain.csv')

In [11]:
df.head(10)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1.325376e+09,36.011293,-82.048315,0.0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1.325376e+09,49.159047,-118.186462,0.0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1.325376e+09,43.150704,-112.154481,0.0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1.325376e+09,47.034331,-112.561071,0.0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1.325376e+09,38.674999,-78.632459,0.0
5,5,2019-01-01 00:04:08,4767265376804500,"fraud_Stroman, Hudson and Erdman",gas_transport,94.63,Jennifer,Conner,F,4655 David Island,...,40.3750,-75.2045,2158,Transport planner,1961-06-19,189a841a0a8ba03058526bcfe566aab5,1.325376e+09,40.653382,-76.152667,0.0
6,6,2019-01-01 00:04:42,30074693890476,fraud_Rowe-Vandervort,grocery_net,44.54,Kelsey,Richards,F,889 Sarah Station Suite 624,...,37.9931,-100.9893,2691,Arboriculturist,1993-08-16,83ec1cc84142af6e2acf10c44949e720,1.325376e+09,37.162705,-100.153370,0.0
7,7,2019-01-01 00:05:08,6011360759745864,fraud_Corwin-Collins,gas_transport,71.65,Steven,Williams,M,231 Flores Pass Suite 720,...,38.8432,-78.6003,6018,"Designer, multimedia",1947-08-21,6d294ed2cc447d2c71c7171a3d54967c,1.325376e+09,38.948089,-78.540296,0.0
8,8,2019-01-01 00:05:18,4922710831011201,fraud_Herzog Ltd,misc_pos,4.27,Heather,Chase,F,6888 Hicks Stream Suite 954,...,40.3359,-79.6607,1472,Public affairs consultant,1941-03-07,fc28024ce480f8ef21a32d64c93a29f5,1.325376e+09,40.351813,-79.958146,0.0
9,9,2019-01-01 00:06:01,2720830304681674,"fraud_Schoen, Kuphal and Nitzsche",grocery_pos,198.39,Melissa,Aguilar,F,21326 Taylor Squares Suite 708,...,36.5220,-87.3490,151785,Pathologist,1974-03-28,3b9014ea8fb80bd65de0b1463b00b00e,1.325376e+09,37.179198,-87.485381,0.0

In [12]:
df['TotalPrice'] = df['amt']
df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,TotalPrice
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1.325376e+09,36.011293,-82.048315,0.0,4.97
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1.325376e+09,49.159047,-118.186462,0.0,107.23
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1.325376e+09,43.150704,-112.154481,0.0,220.11
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1.325376e+09,47.034331,-112.561071,0.0,45.00
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1.325376e+09,38.674999,-78.632459,0.0,41.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596834,596834,2019-09-09 22:57:42,4173950183554608,"fraud_Stanton, Jakubowski and Baumbach",shopping_net,7.10,Stephen,Marshall,M,47144 Roberts Keys,...,-73.9809,3279,Health promotion specialist,1978-10-05,3d75ce52a4708d6a35fc58ffc665a259,1.347231e+09,40.338153,-73.924157,0.0,7.10
596835,596835,2019-09-09 22:58:55,3512365128314616,fraud_Schumm PLC,health_fitness,12.46,Francisco,Kemp,M,9554 Flores Drive,...,-90.3870,35439,Land/geomatics surveyor,1985-03-31,eeb22521ad5d5fe921d6135419fce30f,1.347232e+09,39.386617,-90.926675,0.0,12.46
596836,596836,2019-09-09 23:00:02,4670613943676271,"fraud_Brown, Homenick and Lesch",health_fitness,4.64,Bianca,Novak,F,0953 David Skyway,...,-84.7936,5726,Fitness centre manager,1947-08-14,4a4cd8077e8c608dcbf5a5b10f2e4819,1.347232e+09,30.939766,-84.214233,0.0,4.64
596837,596837,2019-09-09 23:00:09,30199621383748,fraud_Renner Ltd,home,29.14,Theresa,Powell,F,117 Natasha Vista Suite 936,...,-96.2238,4090,Sub,1977-03-23,fb2bfa67036b522a63f0f03224b49d43,1.347232e+09,34.058505,-95.323830,0.0,29.14
596838,596838,2019-09-09 23:00:33,6011542681743618,fraud_Jast-McDermott,shopping_pos,4.32,Emily,Hall,F,8851 Reese Neck,...,-78.7776,863,"Engineer, mining",1972-08,NaN,NaN,NaN,NaN,NaN,4.32

In [13]:
import numpy as np
TotalTransaction = df["TotalPrice"]
TotalTransaction[np.abs(TotalTransaction) > 30.0]

1         107.23
2         220.11
3          45.00
4          41.96
5          94.63
           ...
596827     33.94
596830    157.22
596831     89.53
596832     55.07
596833    148.52
Name: TotalPrice, Length: 365255, dtype: float64

In [14]:
df[np.abs(TotalTransaction) > 674.1112]

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,TotalPrice
232,232,2019-01-01 02:54:10,4311368326621416041,fraud_Kassulke PLC,shopping_net,1055.47,Phillip,Delacruz,M,26678 Lisa Locks Apt. 904,...,-103.0968,648,Community arts worker,1969-09-21,adca67d0a40b26fb8afeccbae31b7828,1.325386e+09,39.940564,-103.528231,0.0,1055.47
296,296,2019-01-01 03:51:28,571844099986,fraud_Heathcote LLC,shopping_net,909.66,Susan,Mills,F,005 Cody Estates,...,-85.7476,736284,Engineering geologist,1952-04-02,ecea96ae40920997dd56b4e0b408d623,1.325390e+09,39.081318,-86.301580,0.0,909.66
511,511,2019-01-01 06:43:54,4509142395811241,fraud_McGlynn-Heathcote,misc_net,1636.87,Margaret,Williams,F,165 Jerry Meadows Suite 460,...,-82.1982,1324,"Engineer, technical sales",1926-07-12,9b13fb1ce565b55afe4106ecdee9346b,1.325400e+09,31.608415,-83.145823,0.0,1636.87
723,723,2019-01-01 09:23:55,4265776278887457,"fraud_Rippin, Kub and Mann",misc_net,1047.52,Christine,Best,F,68248 Deanna Land,...,-92.2123,969,"Physicist, medical",1954-01-05,bb5654f0f82ace48aa6e4f45db7c64c5,1.325410e+09,34.887449,-92.623326,0.0,1047.52
770,770,2019-01-01 09:53:44,38580485618059,fraud_Mohr-Bayer,shopping_net,767.18,Teresa,Clark,F,1323 Derek Mission,...,-103.0098,248,Industrial/product designer,1968-05-13,870bcb4a789f5afcbf32fbe3f49abe89,1.325412e+09,49.342568,-103.496454,0.0,767.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596400,596400,2019-09-09 20:21:14,6011329966782895,fraud_Pagac LLC,shopping_pos,2465.30,Lauren,Butler,F,030 Seth Divide Suite 355,...,-96.0602,413574,"Teacher, special educational needs",1971-09-01,76f76e1a3e4abe579de6899d13b94496,1.347222e+09,35.422765,-96.223832,0.0,2465.30
596631,596631,2019-09-09 21:44:01,676314217768,"fraud_Labadie, Treutel and Bode",shopping_net,1161.72,Ellen,Carrillo,F,9431 Amanda Mills,...,-93.9757,9512,Clinical research associate,1972-12-31,9baae4ac1075a48ca2344b918cbf1aed,1.347227e+09,39.103236,-93.884717,0.0,1161.72
596731,596731,2019-09-09 22:22:33,30499715231997,fraud_Schmitt Ltd,misc_net,750.82,Austin,Phillips,M,89871 Woodard Spring Suite 714,...,-77.8781,9141,Personnel officer,1938-03-15,bc3df4355dc7e9ca639a8b710aeaab03,1.347229e+09,38.147333,-78.007320,1.0,750.82
596806,596806,2019-09-09 22:48:17,30199621383748,"fraud_Bahringer, Schoen and Corkery",shopping_pos,853.57,Theresa,Powell,F,117 Natasha Vista Suite 936,...,-96.2238,4090,Sub,1977-03-23,315c37cc3a0ffee6fb00b760bfdeba33,1.347231e+09,33.053693,-95.372775,0.0,853.57
596812,596812,2019-09-09 22:49:38,30499715231997,fraud_Schumm PLC,shopping_net,970.36,Austin,Phillips,M,89871 Woodard Spring Suite 714,...,-77.8781,9141,Personnel officer,1938-03-15,665c9cafd86dd5c45f222d3309daf0f8,1.347231e+09,37.813031,-78.827451,1.0,970.36